---
- hosts: localhost
  become_user: ubuntu
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: Take Dump
    become: ubuntu
    community.mysql.mysql_db:
     name: pms2
     state: dump
     target: "{{ lookup('pipe','date +%d_%m_%Y') }}_pms.sql"
     login_host: pms.ctuqhqzbzpnq.ap-south-1.rds.amazonaws.com
     login_user: pms2
     login_password: {{ password }}
     dump_extra_args: "--set-gtid-purged=OFF"

  - name: Simple PUT operation
    amazon.aws.aws_s3:
     ignore_nonexistent_bucket: True
     bucket: pms.pearlthoughts-backup
     object: "{{ lookup('pipe','date +%d_%m_%Y') }}_pms.sql"
     src: "./{{ lookup('pipe','date +%d_%m_%Y') }}_pms.sql"
     mode: put
