---

- name: Run the test playbook
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Get the username running this playbook
      become: false
      shell: aws secretsmanager get-secret-value --secret-id MySecret| jq --raw-output '.SecretString' | jq -r .username
      register: username_on_the_host

    - name: Display the User name
      ansible.builtin.debug:
        msg: "Hello User {{ password }} from Jenkins and Ansible!!"
